# Site settings
title: Javier Bravo
description: 'Software Engineer </br> Active · Ambitious · Enthusiast </br> #limitless'
url: 'http://javierbravo.me'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Javier Bravo'
  email: javibravo85@gmail.com
  twitter_username: _javierbravo_
  github_username:  javibravo
  linkedin_username:  javibravo
  show_blog: False
  show_rss: False

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
